version: '3.9'
services:
  acme-db:
    image: postgres
    restart: always
    container_name: acme-db
    ports:
      - 5435:5432
    environment:
      POSTGRES_DB: acme
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
